### ISSUE TITLE
GlucoTracker Not Pulling Data From NightScout Server

### ISSUE THREAD

**Issue by daktau** [HanSolo/Gluco-Tracker#9]
Hi Gerrit, 
Would hyphens “-“ in the URL of my NightScout server cause the app to not connect?

My NightScout server URL resolves fine in a browser but the app I downloaded yesterday is failing to pull any data from it.

Many thanks ,
George

**Comment by HanSolo** [comment]
Hi George, 
No it should not be a problem, tested several urls and they all worked. Can you provide the url so that I can test it? My mail is han dot solo dot gg at gmail dot com

**Comment by HanSolo** [comment]
Do you use a specific port different from 80?

**Comment by daktau** [comment]
Here is the screen shot.

I have altered any port setting on my phone for the GlocoTracker app so it
what ever the default is.

Thanks,
George

**Comment by HanSolo** [comment]
Ok, thx for the url will check what the error is and fix it asap...so stay tuned

**Comment by HanSolo** [comment]
Looks like you use the miao miao transmitter with the freestyle libre sensor. Probably it‘s just a missing field, will fix it tomorrow morning.

**Comment by daktau** [comment]
Excellent! Thanks very much. Vielen Dank!

**Comment by HanSolo** [comment]
After investigating the problem I found that one field in the json response was send as an integer from the miaomiao transmitter. All other json responses I saw so far send the same field as string. The field is "sysTime" and as long as all json entries in a response now are in the same format it works. Meaning to say I saw that you changed from using Xdrip to Tomato and both programs use different format for "sysTime". xDrip sends it as a string where Tomato sends it as an integer. That leads to the problem when changing the transmitter with different formats I cannot parse this field easily. I've made a test with your url and most of the functionality is working now. The only thing that does not work right now is the hbac1 and pattern calculation because this takes values from the last 30 days. And within that range you have changed from xDrip to Tomato and that leads to different formats in one response. So I think I will remove the "sysTime" field completely in the future which will enable the full functionality event when changing transmitters. Might take the weekend to finish that...so stay tuned and in the meantime you can use the Version 3.2 which is currently in review by Apple

**Comment by HanSolo** [comment]
Hi there, forget my last comment, I've removed the field and now it works fine with your url. So wait for 3.3 to come in the app store hopefully today.

**Comment by daktau** [comment]
Ok, many thanks Gerrit. Obviously I’m unfamiliar with the code and how you handle the REST data and how sysTime is employed in how averages are worked out, HBA1C etc BUT if I can be of help in coding a handler function which formats the sysTime field to be whatever the app is expecting no matter what the client sends then I am here to help. 

The app really needs to be able to handle as many clients as possible ideally or it needs to list what it is exclusive to in the App Store. 

Huge thanks for your response to my query. I shall start to use V3.2 and V3.3 when it’s ready. 

Cheers,
George

**Comment by daktau** [comment]
Hi Again Gerrit,
I have forked the code so I can look at it but unfortunately do not have a
Mac. Unless Apple provides a platform to run code on online then I will be
unable to add any code for the time being.

One comment on the iWatch which I am sure you are aware of, is that to
overcome Apples grip on their hardware’s functionality you create a
calendar  event which is always updated to be the current time. This can
then display the glucose reading in real time 24/7 and requires the user to
use the calendar complication. Apologies if you were already aware.

I have an old Mac Mini around somewhere so may fire it up to see if it can
still handle xCode/Swift.

Enjoy the weekend,
George

**Comment by HanSolo** [comment]
Well the problem in your case really was related to the sysTime field which was simply formatted in different ways dependent on what transmitter was used. Because I do not really use this field anywhere I simply removed it which automatically fixed all problems related to that. I have a version of the app that uses a calendar entry already but here I ran into the problem that on the iPhone the background service triggering is also restricted by Apple. The only reliable way to update the calendar entry would be to use push notifications which will start the app in the background and do all the stuff that is needed to make sure it will get updated everywhere. In my solution everything relies on the background task but the execution of this is not guaranteed which leads to strange effects. For that reason I never published this version. I also build the app mainly for our son. So for me the current updates on the watch face complications are ok because I can simply tap the complication which will open the app and by another tap I can get the current version on the watch which is good enough for me and also for our son. He needs to be able to check his glucose value during school lessons without using the phone (he is 11 yrs). 
If you encounter other problems, please do not hesitate to contact me or file an issue.

Cheers and have a great weekend too,

Gerrit
